#开发环境配置

server:
  # 服务端口
  port: 5000


spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    # url: jdbc:mysql://127.0.0.1:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://rm-bp1krwifq9qa102smro.mysql.rds.aliyuncs.com:3306/sleeve?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF8
#    username: chen_root
#    password: "@Chen2021"
#    driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
     username: root
     password: 123456
# 开启权限拦截
auth:
  enabled: true


# 开启http请求日志记录
request-log:
  enabled: true


logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录
    io.github.talelin.latticy.mapper: debug

task:
  # 秒 分 时 日 月 周
  lucene-time: '*/5 * * * * ?'




